export const championAliases: Record<string, string> = {
  'cho gath': "Cho'Gath",
  'kog maw': "Kog'Maw",
  'kai sa': "Kai'Sa",
  'kha zix': "Kha'Zix",
  'rek sai': "Rek'Sai",
  'ksante': "K'Sante",
  'jarvan iv': 'Jarvan IV',
  'lee sin': 'Lee Sin',
  'master yi': 'Master Yi',
  'miss fortune': 'Miss Fortune',
  'twisted fate': 'Twisted Fate',
  'dr mundo': 'Dr. Mundo',
  'dr mundoo': 'Dr. Mundo',
  'tahm kench': 'Tahm Kench',
  'vel koz': "Vel'Koz",
  'xin zhao': 'Xin Zhao',
  'renata': 'Renata Glasc',
  'monkey king': 'Wukong',
  'wu kong': 'Wukong',
  'maokai': 'Maokai',
  'aurelion sol': 'Aurelion Sol',
  'miss fortunee': 'Miss Fortune',
  'le blanc': 'LeBlanc',
  'kai saa': "Kai'Sa",
  'katarina': 'Katarina',
  'kennen': 'Kennen',
  'kenan': 'Kennen',
  'kennenn': 'Kennen',
  'cannon': 'Kennen',
  'canon': 'Kennen',
  'otroks': 'Aatrox',
  'orthodox' : 'Aatrox',
  'atroks': 'Aatrox',
  'aatrox': 'Aatrox',
  'audi' : 'Ahri',
  'audio': 'Ahri',
  'audie' : 'Ahri',
  'are calling': 'Akali',
  "I' ll call you": 'Akali',
  "i'll call you": 'Akali',
  'Akhali': 'Akali',
  'auction': 'Akshan',
  "i'll start": 'Alistar',
  'all star': 'Alistar',
  'any': 'Annie',
  'a failures': 'Aphelios',
  'a failure': 'Aphelios',
  'a fellas': 'Aphelios',
  'a fella': 'Aphelios',
  'ash': 'Ashe',
  'Ash': 'Ashe',
  ' aurelian soul': 'Aurelion Sol',
  'aurelion': 'Aurelion Sol',
  'our alien soul': 'Aurelion Sol',
  'our aliens all': 'Aurelion Sol',
  'our alien': 'Aurelion Sol',
  'aurelian': 'Aurelion Sol',
  'aurelionsol': 'Aurelion Sol',
  'aurelionsoul': 'Aurelion Sol',
  'a brilliant, soul': 'Aurelion Sol',
  'a brilliant soul': 'Aurelion Sol',
  'a brilliant sole': 'Aurelion Sol',
  'a brilliant, sole': 'Aurelion Sol',
  'barred': 'Bard',
  'bard': 'Bard',
};

export const itemAliases: Record<string, string> = {
  'thorn male': 'Thornmail',
  'thorn mail': 'Thornmail',
  'heart steal': 'Heartsteel',
  'heart steel': 'Heartsteel',
  'hardt still': 'Heartsteel',
  'hard steel': 'Heartsteel',
  'you moose': "Youmuu's Ghostblade",
  'youmuu': "Youmuu's Ghostblade",
  'infinity edgee': 'Infinity Edge',
  'force of natures': 'Force of Nature',
  'rogues king': "Ravenous Hydra",
  'black cleaver': 'Black Cleaver',
  'dead mans plate': "Dead Man's Plate",
  'dead man plate': "Dead Man's Plate",
  'spectral cowl': 'Spectral Cowl',
  'morello': "Morellonomicon",
  'morellos': "Morellonomicon",
  'shadow flame': 'Shadowflame',
  '394': 'Trinity force',
  '394s': 'Trinity force',
};

export const commonWhisperMistakes: Record<string, string> = {
  'built thorn male': 'built Thornmail',
  'bought thorn male': 'bought Thornmail',
  'built heart steal': 'built Heartsteel',
  'bought heart steal': 'bought Heartsteel',
  'what should i build': 'what should I build',
  'what do i build': 'what should I build',
  'what should i buy': 'what should I build',
  'enemy build update': 'enemy build update',
};

export const aliases: Record<string, string> = {
  ...championAliases,
  ...itemAliases,
  ...commonWhisperMistakes,
};

